create table if not exists saved_trips (
  id bigint generated by default as identity primary key,
  username varchar(255) not null,
  origin varchar(255) not null,
  destination varchar(255) not null,
  travel_date date not null,
  mode varchar(255) not null,
  origin_airport varchar(255) not null default '',
  destination_airport varchar(255) not null default '',
  risk_level varchar(255),
  risk_points integer,
  summary varchar(1200),
  assessment_json text not null,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null,
  constraint uk_saved_trip_identity unique (
    username,
    origin,
    destination,
    travel_date,
    mode,
    origin_airport,
    destination_airport
  )
);
