create table trip_notifications (
  id bigint generated by default as identity primary key,
  username varchar(255) not null,
  saved_trip_id bigint not null,
  origin varchar(255) not null,
  destination varchar(255) not null,
  travel_date date not null,
  previous_risk_level varchar(255),
  current_risk_level varchar(255),
  previous_risk_points integer,
  current_risk_points integer,
  message varchar(1200) not null,
  read_at timestamp with time zone,
  created_at timestamp with time zone not null
);

create index idx_trip_notifications_username_created
  on trip_notifications (username, created_at desc);
