create table assessment_history (
  id bigint generated by default as identity primary key,
  username varchar(255) not null,
  origin varchar(255) not null,
  destination varchar(255) not null,
  travel_date date not null,
  mode varchar(255) not null,
  origin_airport varchar(255) not null default '',
  destination_airport varchar(255) not null default '',
  risk_level varchar(255),
  risk_points integer,
  summary varchar(1200),
  assessment_json text not null,
  created_at timestamp with time zone not null
);

create index idx_assessment_history_created
  on assessment_history (created_at desc);

create index idx_assessment_history_username_created
  on assessment_history (username, created_at desc);
